chore: added wash up & wash deploy of wadm.local.yaml pre publish to ghcr, verified working with act, testing gha.

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -1,20 +1,23 @@
 name: build_push
 on:
  push:
-  #   branches:
-  #     - master
-    tags:
-      - 'v*'
+    branches:
+      - master
+    # tags:
+    #   - 'v*'
 
 jobs:
   wash-build:
     runs-on: ubuntu-latest
     env:
-      built_file_name: map-managed-environment_s.wasm
+      CARGO_TERM_COLOR: always
+      test-deploy: wadm.local.yaml
+      wasm-bin: map-managed-environment_s.wasm
     permissions:
       contents: 'write'
       packages: 'write'
     steps:
+      #INFO: setup environment
       - name: checkout
         uses: actions/checkout@v4
       - name: install go
@@ -26,20 +29,21 @@ jobs:
         with:
           tinygo-version: "0.33.0"
           install-binaryen: "false"
+      - name: install cargo
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
       - name: install wash tools
         uses: taiki-e/install-action@v2
         with:
-          tool: wit-bindgen-cli, wasm-tools, wit-deps-cli
+          tool: wit-bindgen-cli, wasm-tools, wit-deps-cli, wash-cli
       - name: download wasm-tools-go
         shell: bash
         run: |
           go mod download github.com/bytecodealliance/wasm-tools-go
           go get go.bytecodealliance.org/cmd/wit-bindgen-go
-      - name: install wash-cli
-        shell: bash
-        run: |
-          curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash
-          sudo apt install wash
+      #INFO: generate files
       - name: wit-deps
         shell: bash
         run: |
@@ -52,6 +56,7 @@ jobs:
         shell: bash
         run: |
            go mod tidy
+      #INFO: Validate component yamls
       - name: validate-yaml
         shell: bash
         run: |
@@ -61,14 +66,34 @@ jobs:
         shell: bash
         run: |
           wash build
-      - name: publish package to github repository
-        env:
-          WASH_REG_USER: ${{ github.repository_owner }}
-          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+        #INFO: wash test module isolated 
+      - name: test component load
         shell: bash
         run: |
-           wash push ghcr.io/${{ github.repository }}:${{ github.ref_name }} ${{ env.built_file_name }} --annotation org.opencontainers.image.source=${{github.server_url}}/${{ github.repository }}
-        working-directory: build
-
-#TODO: run wash up, wash apply and check output for success messages
-
+          set -xe
+          wash up &
+          WASH_PID=$!
+          sleep 10;
+          wash app deploy ${{ env.test-deploy }};
+          TRIES=0
+          while [[ $(wash get inventory --output=json | jq '.inventories[0].components | length') -eq 0 ]] ; do
+            if [[ $TRIES -gt 10 ]]; then
+              echo "❌ failed to find component in inventory output after deploying example manifest";
+              exit -1;
+            fi
+            TRIES=$((TRIES+1));
+            sleep 1;
+          done;
+          echo "✅ successfully started at least one component";
+          wash app delete ${{ env.test-deploy }};
+          kill $WASH_PID;
+          exit 0;
+      # #INFO: publish package to ghcr
+      # - name: publish package to github repository
+      #   env:
+      #     WASH_REG_USER: ${{ github.repository_owner }}
+      #     WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+      #   shell: bash
+      #   run: |
+      #      wash push ghcr.io/${{ github.repository }}:${{ github.ref_name }} ${{ env.wasm-bin }} --annotation org.opencontainers.image.source=${{github.server_url}}/${{ github.repository }}
+      #   working-directory: build
